@server = http://localhost:3000

### getOperation
POST {{server}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "getOperation",
    "params": ["1"],
    "id": 1
}

### postOperation
POST {{server}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "postOperation",
    "params": [{
        "operationType": "TRANSFER",
        "memo": "testing transfer API",
        "entries": [
            {
                "bookId": "1",
                "assetId": "btc",
                "value": "-0.2"
            },
            {
                "bookId": "2",
                "assetId": "btc",
                "value": "0.2"
            }
        ]    
    }, false],
    "id": 1
}

### postTransfer
POST {{server}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "postTransfer",
    "params": [{
        "fromBookId": "3",
        "toBookId": "1",
        "assetId": "btc",
        "value": "0.2",
        "memo": "testing transfer API"
    }, true],
    "id": 1
}

### getBook
POST {{server}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "getBook",
    "params": ["1"],
    "id": 1
}

### getBalances
POST {{server}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "getBalances",
    "params": ["1", "btc"],
    "id": 1
}

### createBook
POST {{server}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "createBook",
    "params": [{
        "name": "coinswitch_cash",
        "metadata": {} 
    }],
    "id": 1
}
